name: CI
on: push

env:
  TZ: "Europe/Amsterdam"
  CI: "true"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]

    steps:
      - uses: actions/checkout@v2

      - name: Cache .npm
        uses: actions/cache@v1
        env:
          cache-name: cache-dot-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install libgif-dev
        run: sudo apt install libgif-dev

      - name: Setup Node 11.15
        uses: actions/setup-node@v1
        with:
          node-version: 11.15

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.job == 'test'

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t signalen/frontend:dev -t signalen/frontend:$GITHUB_SHA --cache-from signalen/frontend:dev .

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        if: github.repository == 'Signalen/frontend'

      - name: Docker push
        run: |
          docker push signalen/frontend:dev
          docker push signalen/frontend:$GITHUB_SHA
        if: github.repository == 'Signalen/frontend'
