name: CI
on: push

jobs:
  test:
    name: Linting & unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .npm
        uses: actions/cache@v1
        env:
          cache-name: cache-dot-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Set timezone to Europe/Amsterdam
        run: sudo timedatectl set-timezone Europe/Amsterdam

      - name: Install libgif-dev
        run: sudo apt install libgif-dev

      - name: Setup Node 11.15
        uses: actions/setup-node@v1
        with:
          node-version: 11.15

      - name: Install dependencies
        run: npm ci

      - name: Run linting and tests
        run: |
          npm run lint
          npm run test
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker build
        run: docker build -t signalen/frontend:$GITHUB_SHA .

      - name: Docker push
        run: docker push signalen/frontend:$GITHUB_SHA
